- link:
    ~/.config/i3/config:
      force: true
      path: i3/config

- shell:
  - [rm -rf ~/Downloads/i3lock-color]
  - [git clone https://github.com/Raymo111/i3lock-color ~/Downloads/i3lock-color]
  - [cd ~/Downloads/i3lock-color && bash install-i3lock-color.sh]
  - [feh --bg-fill /home/dunc/Pictures/Wallpapers --randomize]
