# NB: With newer versions of Python, globally-installed pip libraries won't work
# Instead, use the apt equivalents like `sudo apt-get install python3-...`
- link:
    ~/.config/pip/pip.conf:
      path: pip/pip.conf

- pip:
    file: pip/requirements.txt
    binary: /usr/bin/pip3
    stdout: true # Print the execution stdout
    stderr: true  # Print the execution stderr
