- link:
    ~/.config/pip/pip.conf:
      path: pip/pip.conf

- pip:
    file: pip/requirements.txt
    binary: /usr/bin/pip3
    stdout: true # Print the execution stdout
    stderr: true  # Print the execution stderr
