- link:
    ~/.config/pip/pip.conf:
      path: pip/pip.conf

- shell:
    - curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o ~/Downloads/get-pip-py2.py
    - python2 ~/Downloads/get-pip-py2.py
    - rm ~/Downloads/get-pip-py2.py
    - python2 -m pip install pynvim

- pip:
    file: pip/requirements.txt
    binary: /usr/local/bin/pip3
