- tap:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/core

- brew:
    - raycast

- shell:
    # Remove the Spotlight keybind
    - |
      /usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist \
        -c "Delete :AppleSymbolicHotKeys:64" \
        -c "Add :AppleSymbolicHotKeys:64:enabled bool false" \
        -c "Add :AppleSymbolicHotKeys:64:value:parameters array" \
        -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 65535" \
        -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 49" \
        -c "Add :AppleSymbolicHotKeys:64:value:parameters: integer 1048576" \
        -c "Add :AppleSymbolicHotKeys:64:type string standard"

- link:
    ~/.config/raycast/raycast.rayconfig: raycast/raycast.rayconfig
